Add github templates
testng-team/testng pull request #1155
Opened 2016-09-14 08:57 UTC by juherr

@cbeust Feel free to comment a lot, because I'm really not an English writer expert ;)

2016-09-14 17:18 UTC, cbeust commented on .github/CONTRIBUTING.md
> +Before open a new issue, did you ask your question on
Before opening

2016-09-14 17:19 UTC, cbeust commented on .github/CONTRIBUTING.md
> +If you double post on both site, please provides the link to the other question to avoid duplicate answer.
If post on both sites, please provide the link to the other question to avoid duplicating the answer.

2016-09-14 17:19 UTC, cbeust commented on .github/CONTRIBUTING.md
> +
Maybe "in a shell window" instead of CLI?

2016-09-14 17:22 UTC, cbeust commented on .github/CONTRIBUTING.md
> +Up to now, only the latest version is supported. Try to reproduce the issue with the latest version.
Not sure how to read this, it seems to self contradict. I suggest:

Always make sure your issue is happening on the latest TestNG version. Bug reports occurring on older versions will not be looked at.

2016-09-14 17:22 UTC, cbeust commented on .github/CONTRIBUTING.md
> +# Are you considered to make a pull-request instead of a issue?
Have you considered sending a pull request instead of filing an issue?

2016-09-14 17:24 UTC, cbeust commented on .github/ISSUE_TEMPLATE.md
> +> Note: up to now, only the latest version is supported
Remove "up to now".

2016-09-14 17:24 UTC, cbeust commented on .github/PULL_REQUEST_TEMPLATE.md
> +Did you think to?
Did you remember to...

2016-09-14 18:25 UTC, juherr commented
Thanks for the review. I will update it asap.

2016-09-15 08:14 UTC, juherr commented
Updated!

2016-09-15 16:07 UTC, cbeust commented on .github/CONTRIBUTING.md
> +If post on both sites, please provide the link to the other question to avoid duplicating the answer.
"If you posted on both sites"

2016-09-15 16:07 UTC, cbeust commented on .github/CONTRIBUTING.md
> +If the problem does not exist with the CLI, first check if the issue exists on the bugtracker of the runner, and open an issue there first:
Replace "CLI" with "shell".

2016-09-15 16:08 UTC, cbeust commented on .github/CONTRIBUTING.md
> +Always make sure your issue is happening on the latest TestNG version. Bug reports occurring on older versions will not be looked at quickly.
I said "will not be looked at" but well, your version is a bit nicer :)

2016-09-15 16:08 UTC, cbeust commented on .github/CONTRIBUTING.md
> +Maybe you can write a runnable test case (check the `src/test/` folder for examples) and propose it in a pull-request
"pull request" (no hyphen)

2016-09-15 16:08 UTC, cbeust requested changes

2016-09-15 16:32 UTC, juherr commented on .github/CONTRIBUTING.md
> +Always make sure your issue is happening on the latest TestNG version. Bug reports occurring on older versions will not be looked at quickly.
Yep ;) I want to explain that issue on the latest version will have more priority.

2016-09-15 20:10 UTC, juherr commented
Update! Thanks again for the review :)

2016-09-15 20:10 UTC, merged