Control Stacktrace verbosity in Xml Reports
testng-team/testng pull request #1229
Opened 2016-11-05 05:41 UTC by krmahadevan

Fixes # .

### Did you remember to?

- [] Add test case(s)
- [X] Update `CHANGES.txt`

Fixes #1228

Providing a new JVM argument named “stacktrace.output.level”
via which one can control the verbosity of stacktrace in 
xml reports.

2016-11-05 06:30 UTC, juherr commented
I like the idea but if I understand well then the fix will impact stacktrace from failed methods too. 
The issue is about stacktrace from succeed methods only.

2016-11-05 07:04 UTC, krmahadevan commented
@juherr - Thanks for pointing it out. I have taken care of this. Can you please help review ?

2016-11-05 14:57 UTC, cbeust commented on src/main/java/org/testng/reporters/XMLSuiteResultWriter.java
> +          xmlBuffer.addCDATA(stackTraces[0]);
Isn't `stackTraces[0]` (and `[1]`) just one frame of the stack trace? I don't understand what makes them short or full...

2016-11-06 12:56 UTC, juherr requested changes
Some esthetic changes and a bit of refactoring of the legacy code, and it will be perfect :)

2016-11-06 12:56 UTC, juherr commented on src/main/java/org/testng/reporters/XMLSuiteResultWriter.java
> +      switch (level) {
In the case of `STACKTRACE_BOTH`, nothing is printed?

2016-11-06 12:56 UTC, juherr commented on src/main/java/org/testng/reporters/XMLSuiteResultWriter.java
>        String[] stackTraces = Utils.stackTrace(exception, false);
Perf/improvment: if the stacktrace is not displayed, `Utils.stackTrace` should not be computed.

2016-11-06 12:56 UTC, juherr commented on src/main/java/org/testng/reporters/XMLSuiteResultWriter.java
> +    return XMLReporterConfig.STACKTRACE_BOTH;
Should be `STACKTRACE_NONE` instead because if `stackTraceoutputMethod = STACKTRACE_BOTH` the method will return `STACKTRACE_SHORT`

2016-11-06 12:56 UTC, juherr commented on src/main/java/org/testng/reporters/XMLSuiteResultWriter.java
> +    if ((stackTraceoutputMethod & XMLReporterConfig.STACKTRACE_SHORT) == XMLReporterConfig.STACKTRACE_SHORT) {
In fact, I don't catch the need if the bit mask: `stackTraceoutputMethod` should already be the good value (check should be done in the setter) and all possible values are already known: `STACKTRACE_NONE`, `STACKTRACE_SHORT`, `STACKTRACE_FULL` and `STACKTRACE_BOTH`.

2016-11-06 12:56 UTC, juherr commented on src/main/java/org/testng/reporters/XMLSuiteResultWriter.java
> +        case XMLReporterConfig.STACKTRACE_SHORT:
I think it is the perfect time to replace `XMLReporterConfig.STACKTRACE_*` by an enum.

2016-11-07 05:11 UTC, krmahadevan commented on src/main/java/org/testng/reporters/XMLSuiteResultWriter.java
>        String[] stackTraces = Utils.stackTrace(exception, false);
Fixed this.

2016-11-07 05:12 UTC, krmahadevan commented on src/main/java/org/testng/reporters/XMLSuiteResultWriter.java
> +      switch (level) {
Fixed this.

2016-11-07 05:12 UTC, krmahadevan commented on src/main/java/org/testng/reporters/XMLSuiteResultWriter.java
> +        case XMLReporterConfig.STACKTRACE_SHORT:
Took care of this.

2016-11-07 05:12 UTC, krmahadevan commented on src/main/java/org/testng/reporters/XMLSuiteResultWriter.java
> +    return XMLReporterConfig.STACKTRACE_BOTH;
Fixed this.

2016-11-07 05:21 UTC, krmahadevan commented
@juherr - I have fixed all your review comments. Please let me know if there is anything that is missing from my side.

2016-11-07 08:31 UTC, juherr approved these changes
Awesome job, thanks! 👍

2016-11-07 08:31 UTC, juherr commented on src/main/java/org/testng/reporters/XMLReporterConfig.java
> +      throw new IllegalArgumentException(level + " is not a valid StackTrace level");
Proposition: warn + using NONE if level < NONE and BOTH if level > BOTH

2016-11-07 17:59 UTC, cbeust commented on src/main/java/org/testng/reporters/XMLSuiteResultWriter.java
> +          xmlBuffer.addCDATA(stackTraces[0]);
Ok got it, thanks for the clarification.

2016-11-07 20:30 UTC, juherr commented
LGTM :+1: Ping @cbeust

2016-11-07 21:17 UTC, merged