while set parallel to classes the program may occur the exception:
testng-team/testng pull request #1302
Opened 2017-01-18 04:39 UTC by jianhua3331

Set parallel = "classes" and "thread-count = 20".
If there are a lot of testcase failed or throw skiptest, the program may occur the exception(Lots):
java.util.ConcurrentModificationException
at java.util.Hashtable.next(Hashtable.java:1167)
at org.testng.internal.Invoker.classConfigurationFailed(Invoker.java:401)
...

Fixes # .

### Did you remember to?

- [ ] Add test case(s)
- [ ] Update `CHANGES.txt`

2017-01-18 09:42 UTC, juherr requested changes
I suppose the issue is too random to be able to have a non-regression test but `CHANGES.txt` must be updated.

2017-01-18 09:42 UTC, juherr commented on src/main/java/org/testng/internal/Invoker.java
> +    synchronized(this){
As I know, `synchronized(this)` is not a good practice, and in your case, you just want a synchronization on `m_classInvocationResults`.

2017-01-20 07:57 UTC, juherr commented
@jianhua3331 Why did you close the pull request?

2017-01-20 08:05 UTC, jianhua3331 commented
Sorry, I have not seen the message before close it.
I mistakenly think the submission was rejected.
Is it Only need to add the CHANGES.txt in this pull request?

2017-01-20 08:08 UTC, juherr commented
Yep, and I'd like to be sure about `synchronized(this)` too. I'm not feeling it good for the moment.

If you are able to make a test, it will be perfect but as I said, I'm not sure it is possible.

BTW, few effort before the merge IMO ;)

2017-01-20 08:16 UTC, jianhua3331 commented
I have test it in our project and the problem is resolved.
We have a recurring scene which will throw much of SkipTest exceptions.

2017-01-20 08:34 UTC, juherr commented
> I have test it in our project and the problem is resolved.

In fact, the idea behind the test is: it must fail before the fix, it must pass after the fix and it will guarantee the detection of the regression in the future.
Could you add one?

Thanks for Change.txt. What about `synchronized(this)`?

2017-01-24 08:00 UTC, jianhua3331 commented on src/main/java/org/testng/internal/Invoker.java
> +    synchronized(this){
Yes, you are right, I changed to synchronization on m_classInvocationResults.

2017-01-24 09:11 UTC, juherr commented on CHANGES.txt
> -﻿Current
Please, keep this line.
And you can add your name to the list. You made the job, you deserve it! :)

2017-01-24 09:29 UTC, juherr approved these changes

2017-01-24 09:29 UTC, juherr commented
LGTM 👍 Ping @cbeust

2017-01-24 15:18 UTC, cbeust commented on CHANGES.txt
> +Fixed: GITHUB-1302: while set parallel to classes the program may occur the exception(Jianhua Li)
Rephrase: "When 'parallel' is set to 'classes', `ConcurrentModificationException` can be thrown.

2017-01-25 04:01 UTC, merged