Priority order broken when combined with dependencies that have failures
testng-team/testng pull request #1354
Opened 2017-02-25 08:59 UTC by krmahadevan

Fixes #1334 

### Did you remember to?

- [X] Add test case(s)
- [X] Update `CHANGES.txt`

2017-02-25 08:59 UTC, krmahadevan commented
ping @juherr

2017-02-25 11:49 UTC, juherr requested changes
I'm not feeling good the fix. I think it is not fixing the root issue.

2017-02-25 11:49 UTC, juherr commented on src/main/java/org/testng/internal/TestMethodWorker.java
> +    List<IMethodInstance> localMethodInstances = Lists.newArrayList(testMethods);
The order is supposed to be managed by the graph when we add edges.

At the opposite, I'm trying to remove all other locations where an ordering is done: https://github.com/cbeust/testng/pull/1352

2017-02-25 11:49 UTC, juherr commented on src/test/java/test/priority/PriorityTest.java
> +    Assert.assertEquals(TestListener.methods.get(SampleTest01.class), sampleTest01Methods);
Pls, use `InvokedMethodNameListener`

2017-02-25 11:49 UTC, juherr commented on CHANGES.txt
> +Fixed: GITHUB-1334: Priority order broken when combined with dependencies that have failures (Krishnan Mahadevan)
Don't forget to add "Close #xxx" in the commit message. It will close the issue automatically.

2017-02-26 14:51 UTC, krmahadevan commented on src/main/java/org/testng/internal/TestMethodWorker.java
> +    List<IMethodInstance> localMethodInstances = Lists.newArrayList(testMethods);
@juherr - I already tried applying changes part of #1352 before submitting this PR. It does not solve the problem.

2017-02-26 15:08 UTC, krmahadevan commented on src/test/java/test/priority/PriorityTest.java
> +    Assert.assertEquals(TestListener.methods.get(SampleTest01.class), sampleTest01Methods);
Fixed.

2017-02-26 15:15 UTC, krmahadevan commented on CHANGES.txt
> +Fixed: GITHUB-1334: Priority order broken when combined with dependencies that have failures (Krishnan Mahadevan)
Added that in the additional commit.

2017-02-26 17:07 UTC, juherr commented on src/main/java/org/testng/internal/TestMethodWorker.java
> +    List<IMethodInstance> localMethodInstances = Lists.newArrayList(testMethods);
In fact, what I mean is: don't try to sort method outside the graph.
BTW, I propose we add a comment which explains the fix is a workaround for the graph issue and we create a new issue for the graph one with a link to the current pull request.
WDYT?

2017-02-26 17:52 UTC, krmahadevan commented on src/main/java/org/testng/internal/TestMethodWorker.java
> +    List<IMethodInstance> localMethodInstances = Lists.newArrayList(testMethods);
@juherr - I think I may have fixed the ordering properly as part of [this](https://github.com/cbeust/testng/pull/1345/commits/f67cd34170d0daacce7df03a3a7c10a727563656) commit in PR #1345 

Can we first get #1345 merged, and after that I will test out this without sorting and see if that solves the problem ?

2017-02-27 04:56 UTC, cbeust commented on src/main/java/org/testng/internal/TestMethodWorker.java
> +    List<IMethodInstance> localMethodInstances = Lists.newArrayList(testMethods);
@juherr I fully support the idea of linking to Github issues in the source to explain why this code is here.

2017-02-27 07:46 UTC, krmahadevan commented on src/main/java/org/testng/internal/TestMethodWorker.java
> +    List<IMethodInstance> localMethodInstances = Lists.newArrayList(testMethods);
@cbeust - Sure I will do that. But I would like to see if #1345 fixes this problem without needing this PR. So I am waiting for #1345 to be merged before moving forward with this PR.

2017-02-28 18:36 UTC, krmahadevan commented
@juherr - This PR merely adds tests for #1334 (since my PR #1361 fixed this problem). Please help take a look

2017-03-01 03:53 UTC, krmahadevan commented
@cbeust - Can you please help get this merged. This PR contains only tests ? (Trying to wrap up all my existing PRs before starting work on new stuff)

2017-03-01 17:23 UTC, cbeust commented
@juherr had a few doubts about this PR. Julien, you ok with merging this?

2017-03-01 17:40 UTC, krmahadevan commented
@cbeust - Yes that's correct. But after #1361 got merged, this PR didn't require any code change. This PR just adds tests to re-iterate that this issue is really fixed. If you look at the diff, you will see that all the changes are under `src/test/java` only.

2017-03-01 21:53 UTC, merged