Enable URI format for suite location.
testng-team/testng pull request #1544
Opened 2017-09-18 17:55 UTC by krmahadevan

Closes #212

Till now TestNG provided support only for local  file system paths as suite file locations.

Now enabling the location to be specified as a URI.
TestNG will still support only `file:` URI and regular local file system locations, but if one wants
to work with a `http` URI as the suite file locationthen one can provide the location as a URL and then
plug-in an implementation of `org.testng.xml.ISuiteParser` via service loaders and wire in their support for the same.

Fixes #212  .

### Did you remember to?

- [X] Add test case(s)
- [X] Update `CHANGES.txt`

We encourage pull requests that:

* Add new features to TestNG (or)
* Fix bugs in TestNG

If your pull request involves fixing SonarQube issues then we would suggest that you please discuss this with the 
[TestNG-dev](https://groups.google.com/forum/#!forum/testng-dev) before you spend time working on it.

2017-09-18 17:56 UTC, krmahadevan commented
ping @juherr - Please help take a look at this.

2017-09-18 20:18 UTC, juherr reviewed
I think the change will be easier if `toBeParsed` becomes a `List<URI>`.
I understand you don't want to introduce a new interface and the idea is not part of the issue but could you test if it is possible to implement a parser which supports xml files on `http`?

2017-09-18 20:18 UTC, juherr commented on src/main/java/org/testng/xml/Parser.java
> +          scheme = new File(currentFile).toURI().getScheme();
Maybe simplier: `scheme = "file"`?

2017-09-18 20:18 UTC, juherr commented on src/main/java/org/testng/xml/Parser.java
> +        uri =new File(m_fileName).toURI();
Typo: space after '='

2017-09-19 03:29 UTC, krmahadevan commented
@juherr - I have added a test which demonstrates how one can work with suite xml files over `http` (or) `https` protocol.

2017-09-19 06:54 UTC, juherr requested changes
Embedded `ISuiteParser`s should be updated in order to only accept file filename

2017-09-19 06:56 UTC, krmahadevan commented
@juherr 

> Embedded ISuiteParsers should be updated in order to only accept file filename

I didn't understand the comment. Please clarify.

2017-09-19 08:21 UTC, juherr commented
@krmahadevan Sorry. Internal parsers accept "*.xml" files for the moment. That means "http://....xml" will be accepted but it should not.
So, internal parsers must check if the filename starts with "file" too.

2017-09-19 08:32 UTC, krmahadevan commented
@juherr 

> Internal parsers accept "*.xml" files for the moment. That means "http://....xml" will be accepted but it should not.

No that's not the current behavior. TestNG first attempts at iterating through the parsers that were wired in via Service loaders, and only if none of them accept the file, do we default to the default parser viz., `SuiteXmlParser` (Currently TestNG wires in only `org.testng.internal.YamlParser` through service loading mechanism)

Please see below

```java
private static IFileParser getParser(String fileName) {
for (ISuiteParser parser : PARSERS) {
  if (parser.accept(fileName)) {
    return parser;
  }
}

return DEFAULT_FILE_PARSER;
}
```

2017-09-19 08:46 UTC, krmahadevan commented
@juherr - The issue you describe cannot happen with `.xml` but it can very well happen with `.yaml` because our Yaml parser is wired in via service loaders. So, if our end users also build their own `.yaml` parser and would like it to work with `http` (or) `https` then TestNG could still end up feeding it to our built in `.yaml` parser instead of the user fed one because  there's no ordering when service loader loads up the implementations. So I have added the edit check you mentioned, amended the commit and pushed it once again. Please have a look.

2017-09-19 08:48 UTC, juherr approved these changes
👍

2017-09-19 12:02 UTC, merged