[#1616] Testcases with priority and dependsOnGroups dependencies, excution order is chaos
testng-team/testng pull request #1617
Opened 2017-11-17 07:48 UTC by eyehwan

Fixes #1616  .

2017-11-18 10:37 UTC, juherr requested changes
Thanks for the fix 👍

2017-11-18 10:37 UTC, juherr commented on src/test/java/org/testng/internal/dynamicgraph/EdgeWeightTestSample1.java
> +        testCaseExecutionOrder.add(new Object() {}.getClass().getEnclosingMethod().getName());
I think `testCaseExecutionOrder.add("t1)` is more readable and cost less characters ;)

2017-11-18 10:37 UTC, juherr commented on src/test/java/org/testng/internal/DynamicGraphTest.java
> +  public void edgeWeightTest1() {
Can I ask to follow the new test convention (not documented and not the one of the file):
 Instead of static vars, use `InvokedMethodNameListener`.

2017-11-19 03:16 UTC, krmahadevan reviewed
I dont have any additional comments apart from the ones that @juherr has called out. So once the changes request has been taken care of, we should be good.

2017-11-20 03:19 UTC, krmahadevan approved these changes

2017-11-20 03:19 UTC, krmahadevan commented
@eyehwan - Looks like you have conflicts with `CHANGES.txt`. Can you please rebase off of master and update your branch ?

2017-11-20 03:59 UTC, eyehwan commented
@krmahadevan @juherr Thanks for your comments. I have fixed them in last review.

2017-11-21 07:56 UTC, eyehwan commented
@juherr Could you confirm the change I made? Thanks.

2017-11-21 08:22 UTC, juherr approved these changes

2017-11-21 17:32 UTC, merged