Added unit tests for NaN, Max, Min, Positive and Negative Infinity
testng-team/testng pull request #1842
Opened 2018-06-23 04:05 UTC by atulagrawal

Fixes # . https://github.com/cbeust/testng/issues/1734

### Did you remember to?

- [ ] Add test case(s)
- [ ] Update `CHANGES.txt`

We encourage pull requests that:

* Add new features to TestNG (or)
* Fix bugs in TestNG

If your pull request involves fixing SonarQube issues then we would suggest that you please discuss this with the 
[TestNG-dev](https://groups.google.com/forum/#!forum/testng-dev) before you spend time working on it.

2018-06-23 19:01 UTC, juherr requested changes

2018-06-23 19:01 UTC, juherr commented on src/test/java/org/testng/AssertTest.java
> +            Float .NEGATIVE_INFINITY};
You have an extra space here

2018-06-23 19:01 UTC, juherr commented on src/test/java/org/testng/AssertTest.java
> +    float[] expected = {(float) Math.PI, (float) Math.E,Float.MIN_VALUE, Float.MIN_NORMAL, Float.MAX_VALUE, Float.POSITIVE_INFINITY,
And a space is missing here

2018-06-23 19:01 UTC, juherr commented on src/test/java/org/testng/AssertTest.java
> +  @Test(expectedExceptions = AssertionError.class)
It is not the exected behavior from #1734. He'd like to not have an exception.

2018-06-24 15:29 UTC, krmahadevan commented
On a side, please have your PR rebase off of master. I have pushed in a lot
of code formatting changes to master. Just trying to ensure that we don't
run into merge conflicts. --

Thanks & Regards
Krishnan Mahadevan

"All the desirable things in life are either illegal, expensive, fattening
or in love with someone else!"
My Scribblings @ http://wakened-cognition.blogspot.com/

My Technical Scribbings @ http://rationaleemotions.wordpress.com/

2018-06-24 15:36 UTC, atulagrawal commented
One more question - why we don't have public static void assertEquals(float actual, float expected, String message) method implementation? Same goes for double as well?

2018-06-24 19:06 UTC, juherr commented on src/test/java/org/testng/AssertTest.java
> +  @Test(expectedExceptions = AssertionError.class)
A space is missing between methods

2018-06-24 19:14 UTC, juherr commented
> i see that the behavior for NaN value is different for float and double.

We definitely need to fix it.

> Please advise here and I will do the implementation accordingly.

`compareFloatWithNaNValues` must pass without the exception.
 
And I think array tests like `compareDoubleArraysWithNaNValues` should pass without exception too (WDYT @krmahadevan )

> why we don't have public static void assertEquals(float actual, float expected, String message) method implementation? Same goes for double as well?

Because no one added it. Feel free to add the method and its variants.

2018-06-25 04:16 UTC, atulagrawal commented
Thanks @juherr. I have two choices here for fixing above mentioned differences:
1. Covert float to Float Object and compare them using equals method.
2. Use float as primitive only and use "==" operator but have special handling for NaN and Infinity scenarios. Something similar to 
```
public static void assertEquals(double actual, double expected, double delta, String message) {
    // handle infinity specially since subtracting to infinite values gives NaN and the
    // the following test fails
    if (Double.isInfinite(expected)) {
      if (!(expected == actual)) {
        failNotEquals(actual, expected, message);
      }
    } else if (Double.isNaN(expected)) {
      if (!Double.isNaN(actual)) {
        failNotEquals(actual, expected, message);
      }
    } else if (!(Math.abs(expected - actual) <= delta)) {
      failNotEquals(actual, expected, message);
    }
  }
```
The trade off here is between performance and readability. Option 1 will result in more object creations and may cause slight performance issues for very large arrays.

2018-06-25 04:19 UTC, krmahadevan commented
@juherr - I haven't had time to go through this PR and the discussion yet since I was stuck with the formatting changes (I didn't anticipate it to be tiring 😛 ). 
So let me go through the conversation first and then chime in if required with inputs.

2018-06-25 08:35 UTC, juherr commented
@atulagrawal I prefer option 2

2018-06-25 11:17 UTC, atulagrawal commented
@juherr - I have done the changes as per option 2. Can you please review it.

2018-06-25 11:32 UTC, juherr approved these changes
LGTM 👍 

Ping @cbeust

2018-06-25 11:32 UTC, juherr commented on src/main/java/org/testng/Assert.java
> +      assertEquals(actual[i],expected[i], String.format(
space missing after `,`

2018-06-25 18:55 UTC, cbeust reviewed
Looks good to me after the formatting is fixed.

2018-06-25 18:55 UTC, cbeust commented on src/main/java/org/testng/Assert.java
> +                                              ARRAY_MISMATCH_TEMPLATE,
Not sure what the logic for this formatting is, it should just be indented one or possibly two from the previous line.

2018-06-26 02:52 UTC, atulagrawal commented
@cbeust - is it fine now?

2018-06-26 04:55 UTC, merged