GITHUB-2008: Preserve parameters in each class and not all of the test parameters
testng-team/testng pull request #2010
Opened 2019-01-30 13:28 UTC by ausias-armesto

Now the parameters are specify correctly to the testng-failed.xml Report

Fixes # .
https://github.com/cbeust/testng/issues/2008

### Did you remember to?

- [X] Add test case(s)
- [X] Update `CHANGES.txt`

2019-01-30 13:35 UTC, krmahadevan requested changes
Can you please help add a test that validates the changes ? Pls don't forget to add a reference to the newly added test in `src/test/resources/testng.xml`

2019-01-30 18:02 UTC, krmahadevan approved these changes

2019-01-30 20:47 UTC, juherr requested changes
Just follow the convention and we will be able to merge :)

2019-01-30 20:47 UTC, juherr commented on src/main/java/org/testng/reporters/FailedReporter.java
> +    Map<String,  Map<String,  String>> classParameters = new HashMap<String,Map<String,  String>>();
Style issues + prefer to use `Maps`

2019-01-31 08:24 UTC, juherr approved these changes

2019-01-31 08:25 UTC, merged