Streamline data provider information reading
testng-team/testng pull request #2041
Opened 2019-03-23 08:17 UTC by krmahadevan

Closes #1691

Fixes #1691  .

### Did you remember to?

- [X] Add test case(s)
- [X] Update `CHANGES.txt`

We encourage pull requests that:

* Add new features to TestNG (or)
* Fix bugs in TestNG

If your pull request involves fixing SonarQube issues then we would suggest that you please discuss this with the 
[TestNG-dev](https://groups.google.com/forum/#!forum/testng-dev) before you spend time working on it.

2019-03-24 08:44 UTC, krmahadevan commented
ping @juherr

2019-03-24 13:00 UTC, juherr requested changes
Please, add more test cases. 
For example, check the behavior when both class and method have a configured `dataProviderClass` and/or a `dataProvider`.

2019-03-25 03:58 UTC, krmahadevan commented on src/main/java/org/testng/internal/Parameters.java
> +    return annotation.getDataProviderClass() == null || Object.class.equals(annotation.getDataProviderClass());
We can't use `Void` because our annotation by default sets the value to `Object`.

2019-03-25 04:16 UTC, krmahadevan commented
@juherr - I have added more tests. Please take a look.

2019-03-26 12:13 UTC, juherr reviewed
What is the behavior if a class has configured a data provider but test methods don't need it?

The expected behavior is running the tests without any problem.
We can add a test to confirm the behavior.

I wonder if using a data provider on class and having no param method or overring a data provider is a really good idea. Maybe we should warn users against it.

2019-03-26 12:13 UTC, juherr commented on src/main/java/org/testng/internal/Parameters.java
> +    return annotation.getDataProviderClass() == null || Object.class.equals(annotation.getDataProviderClass());
The idea was more to already support Void now and remove Object after.

2019-03-28 04:38 UTC, krmahadevan commented
@juherr 

> What is the behavior if a class has configured a data provider but test methods don't need it?

That was a good catch. I wrote a test for this. 

> The expected behavior is running the tests without any problem.

I dont think that can be made achievable. When a test method inherits a data provider from a class level, and if it doesn't have any arguments defined on it and if the data provider ends up sending argument values, which the test method can't receive, we will now throw an error.  The error message will be verbose enough to let the user know what the issue was. 

> We can add a test to confirm the behavior.

yes I have added a test to confirm the new behavior (that is, the test method errors out) and not the behavior which you are suggesting (which is the test should run without any problem)

I have pushed in the changes as an additional commit. Please help take a look

2019-03-28 12:02 UTC, juherr approved these changes

2019-03-28 12:03 UTC, juherr commented
We should just add a warning in the release note because it will break backward compatibility because current tests may have a data provider on class without problem and it will fail with the next release.

2019-03-28 16:07 UTC, krmahadevan commented
> We should just add a warning in the release note because it will break backward compatibility because current tests may have a data provider on class without problem and it will fail with the next release.

Sure. I will work on starting to compile a release notes which talks about the changes for `7.0.0` and include a reference to this as well.

2019-03-28 16:07 UTC, merged