Fix: alwaysRun should not force invocation of Before-methods
testng-team/testng pull request #2198
Opened 2019-11-23 04:03 UTC by kool79

Resolves cbeust/testng#1622

### Did you remember to?

- [-] Add test case(s)
- [x] Update `CHANGES.txt`

We encourage pull requests that:

* Add new features to TestNG (or)
* Fix bugs in TestNG

If your pull request involves fixing SonarQube issues then we would suggest that you please discuss this with the 
[TestNG-dev](https://groups.google.com/forum/#!forum/testng-dev) before you spend time working on it.

2019-11-23 05:02 UTC, krmahadevan commented
@kool79 - thanks for helping with raising a PR. Can you please include tests as well?

@juherr - please help review. I am out this weekend.

2019-11-24 09:43 UTC, krmahadevan requested changes
There are tests that are failing in this PR. Also please help include a test.

2019-11-25 08:26 UTC, juherr requested changes
Could you add a non-regression test for the feature too?

2026-08-30 19:53 UTC, juherr commented
Thanks for the contribution.

The underlying issue #1622 is still reproducible on current `master`, but this historical patch is no longer the appropriate implementation. In particular, it would also change the `alwaysRun` handling used for disabled test classes, which is behavior required by #420, and the PR never gained the requested regression coverage.

A current implementation with regression tests and red → green → red validation is being handled in #3453.

Closing this PR in favor of #3453. Issue #1622 should remain open until the replacement is merged.

2026-08-30 19:53 UTC, closed without merging