Fix asymmetric not equals
testng-team/testng pull request #2484
Opened 2021-02-26 18:21 UTC by cdalexndr

Fixes #2483 .

### Did you remember to?

- [x] Add test case(s)
- [x] Update `CHANGES.txt`

We encourage pull requests that:

* Add new features to TestNG (or)
* Fix bugs in TestNG

If your pull request involves fixing SonarQube issues then we would suggest that you please discuss this with the 
[TestNG-dev](https://groups.google.com/forum/#!forum/testng-dev) before you spend time working on it.

2021-02-28 16:01 UTC, krmahadevan requested changes
@cdalexndr - Can you please help do the following:

1. Add your name to the `CHANGES.txt`
2. Rebase off of `master` so that we can fix the merge conflicts 

The changes look good.

2021-02-28 20:24 UTC, cdalexndr commented
@krmahadevan done

2021-03-01 03:25 UTC, krmahadevan approved these changes

2021-03-01 03:26 UTC, krmahadevan commented
@juherr - Please help do a quick check.

2021-03-01 07:31 UTC, juherr approved these changes

2021-03-01 17:40 UTC, merged