TestNG 7.4.0 Can not skip test through listener
testng-team/testng pull request #2528
Opened 2021-04-22 13:11 UTC by bj-9527

TestNG 7.4.0 Can not skip test through listener
Fixes #2522 .

### Did you remember to?

- [ ] Add test case(s)
- [ ] Update `CHANGES.txt`

We encourage pull requests that:

* Add new features to TestNG (or)
* Fix bugs in TestNG

If your pull request involves fixing SonarQube issues then we would suggest that you please discuss this with the 
[TestNG-dev](https://groups.google.com/forum/#!forum/testng-dev) before you spend time working on it.

2021-04-25 12:52 UTC, krmahadevan commented
@bj-9527 

Couple of things.

* I remember you had earlier raised another PR on the similar lines as part of https://github.com/cbeust/testng/pull/2423 Is this PR addressing the same problem (A test is not being skipped via a `SkipException` being thrown from a listener) or is this addressing something else ?
* Can we resurrect the original PR and then work on getting that closed (or) you would like to do a fresh start using this PR?
* There are merge conflicts which needs to be fixed via a fetch/rebase

2021-04-26 04:33 UTC, bj-9527 commented
Hi @krmahadevan 

I checked the previous PR  #2423, and compare them with this one, then I think this solution would be better. So I prefer use this one to solve the issue.
I have merged both test cases in each PR, and they are all works fine, and I also rebase the code and please help to review.

2021-04-26 16:08 UTC, juherr requested changes
Some cosmetic remarks on tests

2021-04-27 03:17 UTC, bj-9527 commented on core/src/test/java/test/listeners/github2522/TestListener.java
> +        status.put(testResult.getTestClass().getName() + testResult.getName(), testResult.getStatus());
> Some cosmetic remarks on tests

@juherr Thanks a lot for your comments, I did several change based on that, please help to check.

2021-04-27 03:21 UTC, bj-9527 commented
@juherr Thanks a lot for your comments, I did several change based on that, please help to check.

2021-04-27 05:23 UTC, juherr commented on core/src/test/java/test/listeners/github2522/IssueTest.java
> +@Listeners({TestListener.class})
You can remove the listener

2021-04-27 05:49 UTC, bj-9527 commented on core/src/test/java/test/listeners/github2522/IssueTest.java
> +@Listeners({TestListener.class})
OK, this have been done

2021-04-27 12:59 UTC, juherr approved these changes
LGTM but exceptions are not recommended in listeners.

2021-04-27 12:59 UTC, juherr commented on core/src/test/java/test/listeners/github2522/SkipTestListener.java
> +            throw new SkipException("skip test ...");
It is not recommended to throw exceptions in listeners.
Could you replace it with `result.setStatus(SKIP)` or add another test case.

2021-04-29 07:33 UTC, krmahadevan approved these changes

2021-04-29 07:33 UTC, merged