assertEquals(Set,Set) now ignores ordering as it did before, fixes #2643
testng-team/testng pull request #2648
Opened 2021-10-05 11:40 UTC by Elisedlund-ericsson

see #2643

the https://github.com/cbeust/testng/blob/master/CONTRIBUTING.md is linked from the readme.md but does not exist from what I can see, (so excuse me if I didn't follow the correct WoW)

2021-10-05 11:43 UTC, Elisedlund-ericsson commented on testng-asserts/src/test/java/test/asserttests/AssertTest.java
> -  public void checkSetEqualsFailsWhenDifferentOrder() {
this was just incorrect before

2021-10-05 11:47 UTC, Elisedlund-ericsson commented on testng-asserts/src/test/java/test/asserttests/AssertTest.java
> -  public void checkSetNotEqualsFailsWhenDifferentOrder() {
https://github.com/cbeust/testng/pull/2648

2021-10-25 03:20 UTC, krmahadevan approved these changes

2021-10-28 06:42 UTC, juherr requested changes
Update tests in order to check both `GITHUB-2540` and `GITHUB-2643`.

2021-10-28 07:19 UTC, juherr requested changes

2021-10-28 09:16 UTC, merged