Fixed: #2669
testng-team/testng pull request #2671
Opened 2021-11-13 03:00 UTC by bj-9527

A failed retry with ITestContext will lose the ITestContext

Fixes # 2669.

### Did you remember to?

- [ ] Add test case(s)
- [ ] Update `CHANGES.txt`

We encourage pull requests that:

* Add new features to TestNG (or)
* Fix bugs in TestNG

If your pull request involves fixing SonarQube issues then we would suggest that you please discuss this with the 
[TestNG-dev](https://groups.google.com/forum/#!forum/testng-dev) before you spend time working on it.

2021-11-13 03:35 UTC, krmahadevan commented
@bj-9527 Thanks for the PR. CN you please check if there are any formatting failures? It looks like the tests didn't run

2021-11-13 04:57 UTC, krmahadevan commented on testng-core/src/test/java/test/retryAnalyzer/github2669/IssueTest.java
> +public class IssueTest extends SimpleBaseTest {
Can you please remove this test class and instead add this test method (with a description that refers to the github issue) inside `test.retryAnalyzer.RetryAnalyzerTest` ? We would like to get away from this practise of having all these `IssueTest` but instead have one class that has tests for everything.

2021-11-13 04:58 UTC, krmahadevan commented on testng-core/src/test/java/test/retryAnalyzer/github2669/IssueTest.java
> +    String testngXmlPath = getPathToResource("xml/github2669.xml");
Why not work with the XmlSuite and XmlTest instead? That would be a lot more easier with respect to keeping the details of the test within the confines of this test method itself and not have to worry about all these extra suite files.

2021-11-13 04:59 UTC, krmahadevan commented on testng-core/src/test/java/test/retryAnalyzer/github2669/FailedRetryListener.java
> +        iTestAnnotation.setRetryAnalyzer(FailedRetry.class);
This can be moved within the `catch` block and the printstacktrace part can be removed

2021-11-13 05:00 UTC, krmahadevan commented on testng-core/src/test/java/test/retryAnalyzer/github2669/FailedRetry.java
> +    } else {
else part can be removed and we could just say `retryCount = 1; return false`.

2021-11-13 07:16 UTC, bj-9527 commented
> @bj-9527 Thanks for the PR. CN you please check if there are any formatting failures? It looks like the tests didn't run
> 
> Please refer to https://github.com/cbeust/testng/blob/master/.github/CONTRIBUTING.md for some detailed instructions

Thanks a lot, it really helps.

2021-11-13 08:51 UTC, juherr requested changes

2021-11-13 08:51 UTC, juherr commented on testng-core/src/test/java/test/retryAnalyzer/github2669/FailedRetryListener.java
> +      retry = iTestAnnotation.getRetryAnalyzerClass().newInstance();
This line doesn't compile in jdk >8

2021-11-13 08:51 UTC, juherr commented on testng-core/src/test/java/test/retryAnalyzer/RetryAnalyzerTest.java
> +    Assert.assertEquals(RetryTestSample.count, 3);
I prefer you use a test listener and assert on the sequence of method+status.

2021-11-13 08:51 UTC, juherr commented on testng-core/src/test/java/test/retryAnalyzer/github2669/FailedRetryListener.java
> +public class FailedRetryListener implements IAnnotationTransformer {
I don't get the purpose of this listener

2021-11-13 08:51 UTC, juherr commented on testng-core/src/test/java/test/retryAnalyzer/github2669/RetryTestSample.java
> +  public static int count = 0;
No need of count if you use assertion on listener

2021-11-13 08:51 UTC, juherr commented on testng-core/src/test/java/test/retryAnalyzer/RetryAnalyzerTest.java
> +    XmlSuite suite = createXmlSuite("GITHUB_2669");
You can add a new helper method `createXmlSuite(String name, Map<String, String> params)`

2021-11-14 08:51 UTC, juherr approved these changes

2021-11-14 09:36 UTC, krmahadevan approved these changes

2021-11-14 09:36 UTC, merged

2021-11-14 09:36 UTC, krmahadevan commented
@bj-9527 - Thank you for taking the time to submit this PR. Appreciate it.