Add additional condition for assertEqualsNoOrder
testng-team/testng pull request #2723
Opened 2022-01-30 12:28 UTC by Dymitriux

Add additional condition for assertEqualsNoOrder collection and iterators to check also size

Fixes # .

### Did you remember to?

- [ ] Add test case(s)
- [x] Update `CHANGES.txt`
- [x] Auto applied styling via `./gradlew autostyleApply`

We encourage pull requests that:

* Add new features to TestNG (or)
* Fix bugs in TestNG

If your pull request involves fixing SonarQube issues then we would suggest that you please discuss this with the 
[TestNG-dev](https://groups.google.com/forum/#!forum/testng-dev) before you spend time working on it.

**Note:** For more information on contribution guidelines  please make sure you refer our [Contributing](.github/CONTRIBUTING.md) section for detailed set of steps.

2022-01-30 15:36 UTC, juherr reviewed
Ok for the change but the issue was not detected before by a test.
Could you add one?

2022-01-30 17:44 UTC, Dymitriux commented
Tests added.

2022-01-31 05:23 UTC, juherr approved these changes

2022-01-31 06:19 UTC, krmahadevan approved these changes

2022-01-31 06:21 UTC, krmahadevan requested changes
@Dymitriux - We have failures in tests due to formatting failures.
Please do the following:

1. From the command prompt run `./gradlew autostyleApply`
2. Update this PR with the new changes (the above command will automatically apply formatting changes)
3. Push and let me know once done.

2022-01-31 09:24 UTC, Dymitriux commented
@krmahadevan Formatting changes pushed, sorry for that, forgot about autoStyleApply after adding test cases, now it should be ok.

2022-01-31 09:48 UTC, krmahadevan approved these changes

2022-01-31 09:49 UTC, merged

2022-01-31 09:49 UTC, krmahadevan commented
@Dymitriux - Thanks for taking the time with raising this PR. This is now merged.

2022-01-31 19:37 UTC, Dymitriux commented
@krmahadevan No problem, hope I will find more time for contribution. I will look into issues marked with milestone 7.6.0

2022-02-01 02:20 UTC, krmahadevan commented
@Dymitriux that would be awesome! Looking forward to more contributions from you.