Replace FindBugs by SpotBugs 4.7.1
testng-team/testng pull request #2781
Opened 2022-07-11 21:08 UTC by gruenich

Fixes # .

### Did you remember to?

- [ ] Add test case(s)
- [ ] Update `CHANGES.txt`
- [ ] Auto applied styling via `./gradlew autostyleApply`

We encourage pull requests that:

* Add new features to TestNG (or)
* Fix bugs in TestNG

If your pull request involves fixing SonarQube issues then we would suggest that you please discuss this with the 
[TestNG-dev](https://groups.google.com/forum/#!forum/testng-dev) before you spend time working on it.

**Note:** For more information on contribution guidelines  please make sure you refer our [Contributing](.github/CONTRIBUTING.md) section for detailed set of steps.

2022-07-11 21:10 UTC, gruenich commented
Sorry for the noise. All I wanted to do is to get the GitHub actions running to see what my changes broke.

2022-07-11 21:25 UTC, juherr requested changes

2022-07-11 21:25 UTC, juherr commented on testng-core-api/testng-core-api-build.gradle.kts
> +    api("com.github.spotbugs:spotbugs:4.7.1")
Replace the version by '_'.

2022-07-12 05:08 UTC, gruenich commented on testng-core-api/testng-core-api-build.gradle.kts
> +    api("com.github.spotbugs:spotbugs:4.7.1")
Done, thanks for the hint!

2022-07-12 17:15 UTC, juherr approved these changes

2022-07-12 17:15 UTC, merged