GITHUB-2888 - don't fail test with dataProvider if skipped
testng-team/testng pull request #2889
Opened 2023-03-22 16:29 UTC by jmoreira18

Fixes #2888

If you want to create a listener that would skip a DataProvider in case a Test will be skipped, the Test was marked as FAILED, instead of SKIPPED

### Did you remember to?

- [x] Add test case(s)
- [x] Update `CHANGES.txt`
- [x] Auto applied styling via `./gradlew autostyleApply`

We encourage pull requests that:

* Add new features to TestNG (or)
* Fix bugs in TestNG

If your pull request involves fixing SonarQube issues then we would suggest that you please discuss this with the 
[TestNG-dev](https://groups.google.com/forum/#!forum/testng-dev) before you spend time working on it.

**Note:** For more information on contribution guidelines  please make sure you refer our [Contributing](.github/CONTRIBUTING.md) section for detailed set of steps.

2023-03-22 16:36 UTC, juherr requested changes
Thank for the contribution 👍

2023-03-22 16:36 UTC, juherr commented on testng-core/src/test/java/test/dataprovider/issue2888/SkipDataProviderTest.java
> +public class SkipDataProviderTest extends SimpleBaseTest {
It is a sample, not a test.
Suffix it by Sample instead of Test and remove dependency to SimpleBaseTest.

2023-03-22 16:36 UTC, juherr commented on testng-core/src/test/java/test/dataprovider/issue2888/SkipDataProviderListener.java
> +  private void skipIfSkipMe(ITestNGMethod testNGMethod) {
Could be static

2023-03-22 17:15 UTC, juherr approved these changes

2023-03-23 03:17 UTC, krmahadevan approved these changes

2023-03-23 03:18 UTC, merged