Upgrade snakeyaml to 2.0
testng-team/testng pull request #2903
Opened 2023-04-28 11:50 UTC by labianchin

Includes CVE fix https://bitbucket.org/snakeyaml/snakeyaml/issues/561/cve-2022-1471-vulnerability-in for https://nvd.nist.gov/vuln/detail/CVE-2022-1471

### Did you remember to?

- [ ] Add test case(s)
- [ ] Update `CHANGES.txt`
- [ ] Auto applied styling via `./gradlew autostyleApply`

We encourage pull requests that:

* Add new features to TestNG (or)
* Fix bugs in TestNG

If your pull request involves fixing SonarQube issues then we would suggest that you please discuss this with the 
[TestNG-dev](https://groups.google.com/forum/#!forum/testng-dev) before you spend time working on it.

**Note:** For more information on contribution guidelines  please make sure you refer our [Contributing](.github/CONTRIBUTING.md) section for detailed set of steps.

2023-04-28 13:17 UTC, caesar-ralf approved these changes

2023-04-28 13:18 UTC, caesar-ralf commented
just adding my approval, although probably counts to nothing haha but we would love this change to go out with the security fix

2023-04-28 15:55 UTC, juherr approved these changes

2023-04-28 16:01 UTC, krmahadevan commented
@caesar-ralf this upgrade is causing compilation errors. All tests failed.

2023-04-28 16:01 UTC, krmahadevan requested changes
Can you pls help fix the compilation errors?

2023-05-02 11:18 UTC, labianchin commented
Most build actions are green, but some did fail. The problem is not obvious to me. I do wonder if something is flaky and if we can re-run those tests.

I appreciate any quick help here. I have never used testng (yet), neither I am familiar with the codebase or build setup here.

2023-05-03 14:09 UTC, krmahadevan approved these changes

2023-05-03 14:10 UTC, merged

2023-05-04 08:42 UTC, labianchin commented
Thanks for the help @krmahadevan and @juherr !

Any chance we can have a release with those changes?