Remove deprecated JUnit related support in TestNG
testng-team/testng pull request #3023
Opened 2023-12-27 15:40 UTC by krmahadevan

Closes #3022

Fixes #3022  .

### Did you remember to?

- [ ] Add test case(s)
- [X] Update `CHANGES.txt`
- [ ] Auto applied styling via `./gradlew autostyleApply`

We encourage pull requests that:

* Add new features to TestNG (or)
* Fix bugs in TestNG

If your pull request involves fixing SonarQube issues then we would suggest that you please discuss this with the 
[TestNG-dev](https://groups.google.com/forum/#!forum/testng-dev) before you spend time working on it.

**Note:** For more information on contribution guidelines  please make sure you refer our [Contributing](.github/CONTRIBUTING.md) section for detailed set of steps.

2023-12-27 16:04 UTC, krmahadevan commented
@juherr 
I would perhaps want to merge this maybe after some more time (maybe after a couple of weeks) so that in-case we need to do a bugfix release for `7.9.0` we could do that without this changeset creeping in.

2023-12-27 16:39 UTC, juherr requested changes
Lgtm but remove junit reference from dtd 1.1

2023-12-28 04:43 UTC, krmahadevan commented
> Lgtm but remove junit reference from dtd 1.1

Took care of this as well. Once you have approved after review, I will continue to keep this PR open and rebased so that it can be merged at a later point in time (Perhaps 2nd or 3rd week of Jan).

2023-12-29 07:48 UTC, juherr approved these changes

2024-01-05 07:35 UTC, juherr approved these changes

2024-01-05 07:35 UTC, juherr commented on testng-core/src/main/java/org/testng/TestNG.java
> -          isJUnit = true;
isJUnit declaration should be removed too

2024-01-21 05:39 UTC, merged